"""Service catalog builders for CollaborationDashboardHandler."""

from __future__ import annotations


def _build(namespace, service_names):
    result = {}
    for entry in service_names:
        if isinstance(entry, tuple):
            public_name, symbol_name = entry
        else:
            public_name = entry
            symbol_name = entry
        result[public_name] = namespace[symbol_name]
    return result


TASK_ACTION_SERVICE_NAMES = (
    "perform_task_create",
    "perform_task_preview",
    "perform_task_progress",
    "perform_task_block",
    "perform_task_done",
    "session_for_client",
    "invalidate_dashboard_bundle_cache",
    "invalidate_management_payload_cache",
    "resolve_agent_team_record",
    "merge_tasks",
    "load_config",
    "latest_management_run_for_task",
    "start_task_execution_dispatch",
    "patch_task_team_assignment_metadata",
    "link_task_to_agent_team",
    "get_router_agent_id",
    "perform_task_team_sync",
)

COMMAND_ACTION_SERVICE_NAMES = (
    "SELECTABLE_THEME_CATALOG",
    "apply_agent_team_runtime_policy",
    "auto_selected_skill_slugs_for_message",
    "bootstrap_management_rules",
    "build_chat_thread_quick_snapshot",
    "build_dashboard_state",
    "clean_unique_strings",
    "clear_cached_payloads",
    "compact_chat_thread_detail",
    "create_product_user",
    "conversation_display_session_id",
    "ensure_default_management_bootstrap",
    "ensure_conversation_voice_reply_attachment",
    "ensure_planning_bundle",
    "export_management_weekly_report",
    "find_tenant_record",
    "invalidate_context_hub_payload_cache",
    "invalidate_computer_use_payload_cache",
    "invalidate_dashboard_bundle_cache",
    "invalidate_management_payload_cache",
    "invalidate_openclaw_payload_cache",
    "invalidate_skills_payload_cache",
    "load_config",
    "load_conversation_transcript",
    "load_chat_thread_detail",
    "load_project_metadata",
    "build_management_run_snapshot",
    "load_skills_catalog",
    "merge_chat_message_with_attachments",
    "merge_tasks",
    "merge_team_policy_state",
    "normalize_chat_dispatch_mode",
    "normalize_product_conversation_session_key",
    "normalize_chat_thread_linked_team_ids",
    "normalize_daily_review_schedule",
    "normalize_escalation_steps",
    "normalize_team_runtime_every",
    "normalize_team_runtime_mode",
    "normalize_weekly_report_schedule",
    "normalize_workflow_pack_stages",
    "now_iso",
    "now_utc",
    "open_conversation_session",
    "perform_agent_team_wake",
    "perform_append_rule_backup_channel",
    "perform_append_rule_manual_escalation",
    "perform_browser_create_profile",
    "perform_browser_open",
    "perform_browser_plan",
    "perform_browser_snapshot",
    "perform_browser_start",
    "perform_context_hub_annotate",
    "perform_context_hub_feedback",
    "perform_context_hub_get",
    "perform_context_hub_install",
    "perform_context_hub_search",
    "perform_context_hub_update",
    "perform_computer_use_run_create",
    "perform_computer_use_run_approve",
    "perform_computer_use_answer_clarification",
    "perform_computer_use_run_cancel",
    "perform_computer_use_run_execute",
    "perform_computer_use_run_pause",
    "perform_computer_use_run_resume",
    "perform_computer_use_takeover_action",
    "perform_computer_use_takeover_start",
    "perform_computer_use_takeover_stop",
    "perform_conversation_send",
    "perform_chat_thread_send",
    "perform_openclaw_gateway_probe_refresh",
    "perform_openclaw_browser_probe_refresh",
    "perform_disable_customer_access_channel",
    "perform_customer_channel_voice_test",
    "perform_disable_notification_channel",
    "perform_enable_customer_access_channel",
    "perform_enable_notification_channel",
    "perform_gateway_service_action",
    "perform_insert_workflow_approval_node",
    "perform_management_run_artifact_save",
    "perform_management_run_browser_action",
    "perform_management_run_gate_update",
    "perform_management_run_qa_self_heal",
    "perform_management_run_release_ship",
    "perform_local_model_runtime_configure",
    "perform_local_model_runtime_use_recommended_profile",
    "inspect_local_runtime_model_dir",
    "perform_local_model_runtime_start",
    "perform_local_model_runtime_stop",
    "perform_model_rollout",
    "perform_openclaw_execution_configure",
    "perform_openclaw_speech_runtime_configure",
    "perform_openclaw_speech_runtime_use_local_preset",
    "perform_openclaw_auth_sync",
    "perform_openclaw_cli_install_action",
    "perform_openclaw_provider_setup",
    "perform_pause_automation_rule",
    "perform_runtime_sync_action",
    "perform_set_management_automation_mode",
    "perform_skill_install",
    "perform_skill_package",
    "perform_skill_publish",
    "perform_skill_scaffold",
    "perform_skill_uninstall",
    "perform_strengthen_workflow_handoff_note",
    "perform_transfer_agent_tasks",
    "perform_tune_automation_rule",
    "perform_update_automation_alert_status",
    "perform_workflow_pack_launch_to_chat",
    "perform_workflow_pack_launch_to_run",
    "perform_workflow_pack_launch_to_studio",
    "preview_theme_switch",
    "publish_conversation_stream_event",
    "prepare_chat_send_request",
    "customer_voice_custom_voice_id",
    "recommended_team_id_for_pack_mode",
    "register_installation",
    "remove_installation",
    "requested_team_runtime_mode",
    "resolve_agent_team_record",
    "resolve_chat_dispatch_targets",
    "resolve_chat_thread_participant_agent_ids",
    "resolve_chat_thread_team_records",
    "resolve_pack_launch_target",
    "resolve_planning_project_dir",
    "resolve_run_workflow_binding",
    "resolve_team_default_dispatch_mode",
    "resolve_workflow_pack_or_mode_record",
    "rule_channel_ids",
    "run_automation_engine_cycle",
    "safe_chat_attachments",
    "safe_chat_mentions",
    "safe_chat_reply_context",
    "safe_list",
    "save_agent_team_preserving_meta",
    "save_layered_memory_document",
    "save_agent_voice_reply_sample",
    "schedule_chat_thread_dispatch",
    "send_notification_message",
    "session_for_client",
    "set_agent_paused",
    "set_agent_profile",
    "remove_agent_voice_reply_sample",
    "start_theme_switch_job",
    "store_create_management_run",
    "store_create_tenant_api_key",
    "store_delete_chat_thread",
    "store_get_chat_thread",
    "store_list_agent_teams",
    "store_list_chat_threads",
    "store_restore_orchestration_workflow_version",
    "store_save_automation_rule",
    "store_save_chat_message",
    "store_save_chat_thread",
    "store_save_customer_access_channel",
    ("store_save_management_run", "store_save_management_run_record"),
    "store_save_notification_channel",
    "store_save_orchestration_workflow",
    "store_save_routing_policy",
    "store_save_skill_role_profile",
    "store_save_tenant",
    "store_save_tenant_installation",
    "store_save_workflow_pack",
    "store_update_management_run",
    "summarize_chat_dispatch_result",
    "summarize_notification_target",
    "sync_gstack_skill_library",
    "team_runtime_wake_fields",
    "update_agent_voice_reply_sample_prompt_text",
    "update_product_user_access",
    "workflow_pack_binding_payload",
    "workflow_pack_capabilities",
    "workflow_pack_meta_from_payload",
    "reset_product_user_password",
)

API_READ_SERVICE_NAMES = (
    "chat_thread_attachment_content",
    "conversation_attachment_content",
    "build_activity_snapshot",
    "build_agent_cards_snapshot",
    "build_agent_team_options_snapshot",
    "build_agent_teams_snapshot",
    "build_chat_catalog_page_snapshot",
    "build_computer_use_devices_snapshot",
    "build_computer_use_run_preview_snapshot",
    "build_computer_use_run_actions_snapshot",
    "build_computer_use_runs_snapshot",
    "build_computer_use_run_snapshot",
    "build_computer_use_run_steps_snapshot",
    "build_computer_use_run_artifacts_snapshot",
    "build_communications_audit_snapshot",
    "build_communications_commands_snapshot",
    "build_communications_delivery_snapshot",
    "build_communications_failures_snapshot",
    "build_communications_summary_snapshot",
    "build_communications_terminals_snapshot",
    "build_conversations_catalog_snapshot",
    "build_deliverables_snapshot",
    "build_management_automation_summary_snapshot",
    "build_management_automation_alerts_snapshot",
    "build_management_automation_delivery_snapshot",
    "build_management_automation_rules_snapshot",
    "build_management_decision_intelligence_snapshot",
    "build_management_decision_quality_snapshot",
    "build_management_decision_recommendations_snapshot",
    "build_management_decision_sources_snapshot",
    "build_management_insights_conversations_snapshot",
    "build_management_insights_health_agents_snapshot",
    "build_management_insights_health_summary_snapshot",
    "build_management_recommendations_preview_snapshot",
    "build_management_reports_overview_snapshot",
    "build_management_run_snapshot",
    "build_management_runs_snapshot",
    "build_management_summary_snapshot",
    "build_metrics_snapshot",
    "build_orchestration_overview_snapshot",
    "backfill_planning_bundles",
    "backfill_task_intelligence",
    "build_orchestration_planning_snapshot",
    "build_orchestration_replays_snapshot",
    "build_orchestration_review_snapshot",
    "build_orchestration_routing_snapshot",
    "build_orchestration_suggestions_snapshot",
    "build_orchestration_task_index_snapshot",
    "build_orchestration_workflows_snapshot",
    "cached_payload",
    "cached_payload_background",
    "build_admin_audit_logs_snapshot",
    "build_admin_api_keys_snapshot",
    "build_admin_bootstrap_snapshot",
    "build_admin_installations_snapshot",
    "build_admin_tenants_snapshot",
    "build_admin_users_snapshot",
    "build_external_api_reference",
    "build_platform_runtime_governance_summary",
    "build_platform_runtime_governance_runtimes",
    "build_platform_runtime_governance_packs",
    "build_platform_runtime_governance_browser_sessions",
    "build_theme_snapshot",
    "build_label_maps",
    "compact_chat_thread_detail",
    "compact_task_dashboard_payload",
    "compact_dashboard_bootstrap_payload",
    "compact_openclaw_bootstrap_payload",
    "dashboard_signature",
    "get_router_agent_id",
    "load_agents",
    "load_chat_thread_detail",
    "load_conversation_catalog",
    "load_conversation_transcript",
    "load_config",
    "load_agent_memory_data",
    "load_context_hub_data",
    "load_context_hub_summary_data",
    "load_kanban_config",
    "load_local_runtime_payload",
    "load_model_execution_architecture_payload",
    "load_shared_context_data",
    "load_skills_detail",
    "load_openclaw_control_data_subprocess",
    "load_openclaw_gateway_panel_data",
    "load_openclaw_browser_panel_data",
    "load_openclaw_memory_panel_data",
    "load_openclaw_memory_workflow_panel_data",
    "load_openclaw_dashboard_summary",
    "load_openclaw_message_gateway_panel_data",
    "load_openclaw_sandbox_panel_data",
    "load_openclaw_skill_growth_panel_data",
    "load_openclaw_voice_workflow_panel_data",
    "load_openclaw_runtime_overview_panel_data",
    "load_openclaw_models_panel_data",
    "load_openclaw_local_runtime_panel_data",
    "load_openclaw_orchestration_panel_data",
    "load_openclaw_session_governance_panel_data",
    "load_openclaw_skills_check_panel_data",
    "load_openclaw_agent_params_panel_data",
    "store_list_management_runs",
    "store_list_notification_channels",
    "store_list_orchestration_workflows",
    "merge_tasks",
    "load_skill_pack_detail",
    "load_task_detail",
    "load_theme_switch_status",
    "build_deliverable_zip_bytes",
    "now_utc",
    "safe_list",
)

HTTP_GET_SERVICE_NAMES = (
    "WECHAT_CALLBACK_ROUTE",
    "handle_wechat_customer_access_get",
)

HTTP_POST_SERVICE_NAMES = (
    "WECHAT_CALLBACK_ROUTE",
    "handle_wechat_customer_access_post",
)

REST_GET_SERVICE_NAMES = (
    "build_activity_snapshot",
    "build_agent_cards_snapshot",
    "build_agent_teams_snapshot",
    "build_communications_summary_snapshot",
    "build_conversations_catalog_snapshot",
    "cached_payload",
    "dashboard_signature",
    "build_deliverable_zip_bytes",
    "build_deliverables_snapshot",
    "build_orchestration_task_index_snapshot",
    "build_tenant_admin_data",
    "find_tenant_record",
    "build_management_run_snapshot",
    "build_management_runs_snapshot",
    "build_management_summary_snapshot",
    "get_router_agent_id",
    "load_config",
    "load_context_hub_data",
    "now_utc",
    "tenant_rest_catalog_payload",
)

REST_POST_SERVICE_NAMES = (
    "perform_task_create",
)


def build_task_action_services(namespace):
    return _build(namespace, TASK_ACTION_SERVICE_NAMES)


def build_command_action_services(namespace):
    return _build(namespace, COMMAND_ACTION_SERVICE_NAMES)


def build_api_read_services(namespace):
    return _build(namespace, API_READ_SERVICE_NAMES)


def build_http_get_services(namespace):
    return _build(namespace, HTTP_GET_SERVICE_NAMES)


def build_http_post_services(namespace):
    return _build(namespace, HTTP_POST_SERVICE_NAMES)


def build_rest_get_services(namespace):
    return _build(namespace, REST_GET_SERVICE_NAMES)


def build_rest_post_services(namespace):
    return _build(namespace, REST_POST_SERVICE_NAMES)
